"""channel table update description, create index in message table

Revision ID: 344af4a536eb
Revises: 061bbdfbb84b
Create Date: 2026-04-02 22:33:44.540226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344af4a536eb'
down_revision: Union[str, Sequence[str], None] = '061bbdfbb84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_messages_channel_created_at', 'messages', ['channel_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_channel_created_at', table_name='messages')
    op.alter_column('channels', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
